<?php echo $this->doctype() ?>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

  <?php 

  	echo $this->headTitle();
  	echo $this->headMeta();
?>

<link rel="stylesheet" href="/css/mobile.css" type="text/css" media="handheld, only screen and (max-device-width: 480px)" />

<!--[if !IE]><!-->
	<link href="/css/styles.css" media="screen" rel="stylesheet" type="text/css" />
<!--<![endif]-->
<!--[if IE]>
	<link rel="stylesheet" type="text/css" href="/css/ie.css" />
<![endif]-->

<link rel="shortcut icon" href="http://southvirginiahomes.com/images/favicon.ico" /> 
<link rel="canonical" href="<?php 

$request = Zend_Controller_Front::getInstance()->getRequest()->getActionName();

		if ($request == 'index') 
			echo 'http://southvirginiahomes.com';
		elseif ($request == 'about') 
			echo 'http://southvirginiahomes.com/about';
	    elseif ($request == 'contact') 
			echo 'http://southvirginiahomes.com/contact';
	    else
			echo '';

?>" /> 

<meta name="google-site-verification" content="PsUbRNsU6E-gy33Ctt7sC3y8ONicY9KP0sJY4KspRJ8" />
<meta name="msvalidate.01" content="89CEE778A7138ACD34E85AB8C98873A0" />
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-3173227-12']);
  _gaq.push(['_trackPageview']);
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

</head>

<body>

<div id="image"><img src="/images/luxury-home.jpg" alt=""/></div>
<div id="fb-root"></div>

<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=218261441523608";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div id="mainWrapper">

<table style="padding-bottom:25px;">
<tr>
<td width="50%">
<div align="center">
  <h1>South Virginia Homes</h1>
  <img src="/images/david-boord.jpg" alt="Real Estate Agent David Boord." />
</div>
</td>

<td width="50%" style="padding-left:130px;">
<div align="center">
  <img src="/images/TOW-header.jpg" alt="TOW Logo" style="padding:5px;" /><br />
  <img src="/images/realtor.gif" alt="Realtor" style="padding-right:40px;" /><img src="/images/equal-housing-opportunity.gif" alt="Equal Housing Opportunity." /><br /><br />
  <strong style="font-size:25px;">Call 1-757-926-9171</strong>
</div>
</td>
</tr>
</table>

<?php echo $this->layout()->content ?>

</div>

<div id="FooterArea">
<a name="b" id="b"></a>
<li><a <?php if (Zend_Controller_Front::getInstance()->getRequest()->getActionName() == 'index') { echo 'class="active"'; } else { echo '';} ?> href="/#b">Home</a></li> <li><a <?php if (Zend_Controller_Front::getInstance()->getRequest()->getActionName() == 'about') { echo 'class="active"'; } else { echo '';} ?> href="/about/#b">About</a></li><li><a <?php if (Zend_Controller_Front::getInstance()->getRequest()->getActionName() == 'contact') { echo 'class="active"'; } else { echo '';} ?> href="/contact/#b">Contact</a></li> 

</div>
</body>
</html>