<?php $this->headTitle()->append('About David Boord.'); 
$this->headMeta()->appendName('description', 'David Boord is a Keller Williams agent in the Norfolk and Virginia Beach housing area.'); 
$this->headMeta()->appendName('keywords', 'David Boord, about, Norfolk, Virginia Beach, housing market, real estate agent'); ?>

<fieldset>

<p>I specialize in For Sale By Owner and Military relocation and 1st time home buyers. I have served in the Navy for 14 years and now serve in the Navy Reserves. I understand how stressful moving can be for the military members and families. My job is to help you find a home that meets your needs and wants. Again, thank you and hope we are able to work together in the future.</p>

<p><div class="fb-like-box" data-href="http://www.facebook.com/pages/South-VA-Homes/206760116021795" data-width="292" data-show-faces="false" data-stream="false" data-header="true"></div></p>

</fieldset>